In [ ]:
import sys
a = 3838
print(sys.getrefcount(a))
b = a
print(sys.getrefcount(a))
del(b)
print(sys.getrefcount(a))


In [ ]:
import numpy as np
data = np.random.randn(2,3)
data
data*10
data.shape
data.dtype

data1 = [22, 1, 0, 3, -1]
arr = np.array(data1)
arr.shape






In [ ]:
data2 = [[1,0,2], [3,2,9]]
arr1 = np.array(data2)
arr1.shape
#arr1.ndim

In [ ]:
arr1[1][2]
arr1[1,2]

In [ ]:
arr2 = np.zeros(10)
arr2


In [ ]:
arr3 = np.zeros((3,6))
arr3

In [ ]:
arr4 = np.empty((2,3,2))
arr4

In [ ]:
arr5 = np.arange(15)
arr5.ndim
arr5.shape
arr5

In [ ]:
arr5[5:8] = 66
arr5[5:8]

In [ ]:
arr5_slice = arr5[2:5]
arr5_slice[:] = 100
arr5

In [ ]:
arr6 = np.array([2,1,3],dtype=np.float64)
arr6.astype(np.int32)

In [ ]:
arr7 = np.array(['1.2', '9.0', '99'])
arr7.astype(np.float64)

In [ ]:
data2*2

In [ ]:
arr1**2

In [ ]:
arr1


In [ ]:
arr2

In [ ]:
arr12 = arr1*2
arr12

In [ ]:
arr1>arr12

In [ ]:
arr2


In [ ]:
arr5

In [ ]:
arr3d = [[[1,2,3,3], [3,4,5,1]], [[1,2,3,1], [3,4,5,1]]]
arr3d1 = np.array(arr3d)
arr3d1.ndim
arr3d1.shape

In [ ]:
arr2d = np.empty((3,3))
arr2d


In [ ]:
arr2d[1,1:]

In [ ]:

name = np.array(['bob', 'sam', 'leon'])
datax = np.random.randn(3,2)
datax
#datax.ndim
#name == 'bob'


In [178]:
#fancy indexing
arrf = np.empty((8,4))
for i in range(8):
    for j in range(4):
        arrf[i][j] = i+j+10
arrf

array([[ 10.,  11.,  12.,  13.],
       [ 11.,  12.,  13.,  14.],
       [ 12.,  13.,  14.,  15.],
       [ 13.,  14.,  15.,  16.],
       [ 14.,  15.,  16.,  17.],
       [ 15.,  16.,  17.,  18.],
       [ 16.,  17.,  18.,  19.],
       [ 17.,  18.,  19.,  20.]])

In [192]:
arrf[[2,3]]

array([[ 12.,  13.,  14.,  15.],
       [ 13.,  14.,  15.,  16.]])

In [202]:
arrf[[-1,-3],[1,2]]

array([ 18.,  17.])

In [227]:
arre = np.arange(15)
arre

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [272]:
arre1 = arre.reshape((3,5))
arre1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [271]:
arre1.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [270]:
arre1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])